name: Go CI

on:
  push:
    branches:
      - main
      - one-branch
  pull_request:
    branches:
      - main
      - one-branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"

      - name: Install golangci-lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.55.2/golangci-lint-1.55.2-linux-amd64.tar.gz | tar -xz -C /tmp
          mv /tmp/golangci-lint-1.55.2-linux-amd64/golangci-lint /usr/local/bin/

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Run go fmt
        run: |
          fmt_output=$(go fmt ./...)
          if [ -n "$fmt_output" ]; then
            echo "❌ Code is not formatted properly:"
            echo "$fmt_output"
            exit 1
          else
            echo "✅ Code is properly formatted."
          fi

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"

      - name: Create test data
        run: |
          mkdir -p my-grpc-file-service/internal/service/test_data
          echo "This is an empty file" > my-grpc-file-service/internal/service/test_data/empty.txt

      - name: Run tests
        run: go test -v ./internal/service/...